import type { ClientAction, Deliverable, RiskAlert, WealthClient } from './types'

export const wealthClients: WealthClient[] = [
  { id: 'diaz', name: '周启明', initials: '周', clientNo: 'KH099', aum: '265.8 万元', walletShare: 72, status: '风险关注', segment: '高净值客户', recentContact: '9 月 12 日', nextAction: '今日确认付款资金', favorite: true, isMine: true, accent: '#ef5b6b' },
  { id: 'lauren', name: '林若岚', initials: '林', clientNo: 'KH128', aum: '688.4 万元', walletShare: 52, status: '风险关注', segment: '高净值客户', recentContact: '9 月 16 日', nextAction: '复核资产配置', favorite: true, isMine: true, accent: '#6f63e8' },
  { id: 'allen', name: '王建国', initials: '王', clientNo: 'KH216', aum: '421.0 万元', walletShare: 86, status: '正常服务', segment: '高净值客户', recentContact: '9 月 10 日', nextAction: '季度回顾', favorite: false, isMine: true, accent: '#2f9f86' },
  { id: 'johnson', name: '赵文博', initials: '赵', clientNo: 'KH305', aum: '842.0 万元', walletShare: 31, status: '需跟进', segment: '高净值客户', recentContact: '8 月 28 日', nextAction: '安排年度回顾', favorite: false, isMine: true, accent: '#d28a35' },
  { id: 'morrison', name: '刘志远', initials: '刘', clientNo: 'KH184', aum: '210.0 万元', walletShare: 64, status: '风险关注', segment: '富裕客户', recentContact: '9 月 8 日', nextAction: '更新养老规划', favorite: true, isMine: true, accent: '#d59137' },
  { id: 'hayes', name: '沈嘉成', initials: '沈', clientNo: 'KH072', aum: '510.0 万元', walletShare: 43, status: '需跟进', segment: '私行客户', recentContact: '4 月 24 日', nextAction: '重新建立联系', favorite: true, isMine: true, accent: '#ca7845' },
  { id: 'nguyen', name: '吴思远', initials: '吴', clientNo: 'KH237', aum: '324.0 万元', walletShare: 59, status: '风险关注', segment: '富裕客户', recentContact: '9 月 15 日', nextAction: '核查集中持仓', favorite: false, isMine: true, accent: '#2874d0' },
  { id: 'emily', name: '许知夏', initials: '许', clientNo: 'KH166', aum: '176.0 万元', walletShare: 77, status: '需跟进', segment: '成长客户', recentContact: '9 月 11 日', nextAction: '确认备用金方案', favorite: false, isMine: true, accent: '#329a7b' },
  { id: 'chen-family', name: '陈舒桐', initials: '陈', clientNo: 'KH318', aum: '192.0 万元', walletShare: 68, status: '风险关注', segment: '成长客户', recentContact: '9 月 14 日', nextAction: '更新教育金计划', favorite: false, isMine: false, accent: '#8b74d9' },
  { id: 'zhang-family', name: '张雨桐', initials: '张', clientNo: 'KH329', aum: '380.0 万元', walletShare: 45, status: '需跟进', segment: '富裕客户', recentContact: '6 月 20 日', nextAction: '预约服务回访', favorite: false, isMine: true, accent: '#c27b45' },
  { id: 'li-family', name: '李文静', initials: '李', clientNo: 'KH330', aum: '260.0 万元', walletShare: 62, status: '风险关注', segment: '富裕客户', recentContact: '9 月 10 日', nextAction: '确认续期保费资金', favorite: false, isMine: true, accent: '#4e9b88' },
  { id: 'gaoyuan-tech', name: '高远', initials: '高', clientNo: 'KH105', aum: '455.0 万元', walletShare: 38, status: '风险关注', segment: '私行客户', recentContact: '9 月 17 日', nextAction: '复核行业集中度', favorite: false, isMine: false, accent: '#3978c5' },
]

export const riskAlerts: RiskAlert[] = [
  {
    id: 'diaz',
    customer: '周启明',
    category: '流动性风险',
    categoryEn: '现金流风险',
    priority: '高',
    score: 96,
    impactValue: '16.8 万元',
    impactLabel: '预计资金缺口',
    summary: '购房尾款可能造成现金缺口',
    urgency: '21 天后付款',
    accent: '#e55968',
  },
  {
    id: 'lauren',
    customer: '林若岚',
    category: '投资组合风险',
    categoryEn: '配置偏离',
    priority: '高',
    score: 92,
    impactValue: '+11 个百分点',
    impactLabel: '高于目标配置',
    summary: '权益类资产配置超过目标区间',
    urgency: '今日识别',
    accent: '#e55968',
  },
  {
    id: 'morrison',
    customer: '刘志远',
    category: '目标偏离',
    categoryEn: '养老目标',
    priority: '高',
    score: 88,
    impactValue: '210 万元',
    impactLabel: '相关资产规模',
    summary: '养老储备进度低于计划',
    urgency: '7 天内处理',
    accent: '#e39a42',
  },
  {
    id: 'hayes',
    customer: '沈嘉成',
    category: '客户流失风险',
    categoryEn: '关系维护',
    priority: '中',
    score: 81,
    impactValue: '147 天',
    impactLabel: '距上次有效联系',
    summary: '客户长期未产生有效互动',
    urgency: '已逾期 14 天',
    accent: '#e39a42',
  },
  {
    id: 'nguyen',
    customer: '吴思远',
    category: '投资组合风险',
    categoryEn: '持仓集中',
    priority: '中',
    score: 76,
    impactValue: '140 万元',
    impactLabel: '集中持仓规模',
    summary: '单只主题基金持仓集中度过高',
    urgency: '今日识别',
    accent: '#1677ff',
  },
  {
    id: 'emily',
    customer: '许知夏',
    category: '流动性风险',
    categoryEn: '备用金不足',
    priority: '低',
    score: 68,
    impactValue: '8.2 万元',
    impactLabel: '流动性储备缺口',
    summary: '日常备用金低于建议水平',
    urgency: '30 天内处理',
    accent: '#329a7b',
  },
  {
    id: 'chen-family',
    customer: '陈舒桐',
    category: '目标偏离',
    categoryEn: '教育目标',
    priority: '中',
    score: 64,
    impactValue: '92 万元',
    impactLabel: '教育金预计缺口',
    summary: '教育金储蓄进度落后于计划',
    urgency: '14 天内复核',
    accent: '#8b74d9',
  },
  {
    id: 'zhang-family',
    customer: '张雨桐',
    category: '客户流失风险',
    categoryEn: '沟通中断',
    priority: '中',
    score: 61,
    impactValue: '90 天',
    impactLabel: '未回复服务沟通',
    summary: '连续三次服务沟通未获回应',
    urgency: '已逾期 7 天',
    accent: '#c27b45',
  },
  {
    id: 'li-family',
    customer: '李文静',
    category: '流动性风险',
    categoryEn: '保费支出',
    priority: '低',
    score: 57,
    impactValue: '36 万元',
    impactLabel: '即将支付的保费',
    summary: '续期保费到期前资金不足',
    urgency: '30 天后扣款',
    accent: '#4e9b88',
  },
  {
    id: 'gaoyuan-tech',
    customer: '高远',
    category: '投资组合风险',
    categoryEn: '行业集中',
    priority: '低',
    score: 52,
    impactValue: '27%',
    impactLabel: '科技主题持仓占比',
    summary: '行业集中度超过约定配置上限',
    urgency: '今日识别',
    accent: '#3978c5',
  },
]

export const followUpItems = [
  {
    id: 'call-diaz',
    riskId: 'diaz',
    title: '联系周启明',
    description: '沟通购房尾款的资金来源，并确认调拨方案与执行时间。',
    due: '今日到期',
    action: '发起联系',
    tone: 'error',
  },
  {
    id: 'review-lauren',
    riskId: 'lauren',
    title: '复核林若岚的资产配置',
    description: '对照目标配置准备再平衡方案，确认可调整账户与赎回费用与到账时间。',
    due: '9 月 19 日到期',
    action: '查看组合',
    tone: 'warning',
  },
  {
    id: 'prepare-morrison',
    riskId: 'morrison',
    title: '准备刘志远养老规划复盘',
    description: '更新收入、通胀与退休年龄假设，并整理客户会议确认项。',
    due: '9 月 20 日到期',
    action: '查看计划',
    tone: 'blue',
  },
  {
    id: 'contact-hayes',
    riskId: 'hayes',
    title: '重新联系沈嘉成',
    description: '安排年度服务回顾，确认近期资金安排与新增服务需求。',
    due: '已逾期 14 天',
    action: '联系客户',
    tone: 'error',
  },
  {
    id: 'review-nguyen',
    riskId: 'nguyen',
    title: '核查吴思远的集中持仓',
    description: '评估分批减持路径、赎回费用和替代配置，并形成沟通方案。',
    due: '9 月 21 日到期',
    action: '查看持仓',
    tone: 'warning',
  },
  {
    id: 'prepare-emily',
    riskId: 'emily',
    title: '确认许知夏的备用金方案',
    description: '核对未来三个月支出，补足流动性储备并记录资金安排。',
    due: '9 月 22 日到期',
    action: '准备方案',
    tone: 'blue',
  },
  {
    id: 'update-chen',
    riskId: 'chen-family',
    title: '更新陈舒桐教育金计划',
    description: '获取最新学费预算，重新测算月度储蓄额与投资期限。',
    due: '9 月 23 日到期',
    action: '更新计划',
    tone: 'blue',
  },
  {
    id: 'schedule-zhang',
    riskId: 'zhang-family',
    title: '安排张雨桐服务回访',
    description: '更换联系渠道，确认客户是否需要调整服务频率与沟通方式。',
    due: '9 月 25 日前完成',
    action: '安排回访',
    tone: 'warning',
  },
]

export const clientActions: ClientAction[] = [
  {
    id: 'lin',
    name: '林若岚',
    initials: '林',
    level: '高风险',
    priority: 96,
    aum: '¥1,286 万',
    profile: 'C4 成长型 · 重点客户',
    event: '行业主题基金占可投资资产 46.8%，显著偏离建议上限',
    evidence: '近 30 日波动率升至 21.4%，压力情景下预计组合回撤 14.6%',
    due: '建议今日 12:00 前联系',
    source: '持仓快照 09:10 · 风险引擎 09:12',
    accent: '#f05b66',
  },
  {
    id: 'zhou',
    name: '周启明',
    initials: '周',
    level: '服务机会',
    priority: 89,
    aum: '¥820 万',
    profile: 'C3 稳健型 · 企业主',
    event: '300 万结构性存款将在 3 天后到期，尚未确认续作安排',
    evidence: '账户近 6 个月平均闲置资金 182 万，近期表达稳健增值诉求',
    due: '建议今日 15:00 前沟通',
    source: '产品到期日历 · 沟通纪要 08/28',
    accent: '#7965ff',
  },
  {
    id: 'chen',
    name: '陈舒桐',
    initials: '陈',
    level: '需关注',
    priority: 82,
    aum: '¥2,360 万',
    profile: 'C4 成长型 · 私行客户',
    event: '7 日内连续赎回 120 万，资金用途与流动性需求尚不明确',
    evidence: '赎回金额达到近一年月均支出的 5.2 倍，客户账户未见对应入账',
    due: '建议今天完成需求确认',
    source: '交易流水 T+0 · 客户账户视图',
    accent: '#e89a3d',
  },
  {
    id: 'wang',
    name: '王致远',
    initials: '王',
    level: '需关注',
    priority: 74,
    aum: '¥690 万',
    profile: 'C3 稳健型 · 退休客群',
    event: '风险测评将在 7 天后失效，存在服务与交易中断风险',
    evidence: '上次测评为 2025-09-24，近一年个人收入结构已发生变化',
    due: '9 月 25 日前完成更新',
    source: '客户档案 · 适当性系统',
    accent: '#43a590',
  },
]

export const assetMix = [
  { label: '固收类', value: 42, color: '#6b5cff' },
  { label: '权益类', value: 31, color: '#2fb8c6' },
  { label: '现金及货基', value: 14, color: '#8a7ff4' },
  { label: '另类资产', value: 8, color: '#f1aa54' },
  { label: '保险保障', value: 5, color: '#ef7285' },
]

export const deliverables: Deliverable[] = [
  {
    key: '建议',
    title: '服务建议',
    subtitle: '给出分阶段配置动作与人工确认项',
    prompt:
      '基于林若岚女士当前持仓、C4 风险承受能力、未来 12 个月 150 万教育资金需求，生成可执行的服务建议。严格区分事实、风险判断和行动建议，不承诺收益。',
  },
  {
    key: '提纲',
    title: '沟通提纲',
    subtitle: '生成有温度、可解释的电话沟通结构',
    prompt:
      '为林若岚女士生成 8 分钟电话沟通提纲。先确认资金安排，再解释集中度风险，提供两个可选调整方案，并准备客户可能提出的三个问题。',
  },
  {
    key: '报告',
    title: '客户报告',
    subtitle: '生成客户可读的资产诊断摘要',
    prompt:
      '生成一页客户资产诊断报告，包含资产概览、集中度风险、压力测试、建议配置区间与风险揭示。使用客户能理解的语言，隐藏内部评分。',
  },
  {
    key: '纪要',
    title: '跟进纪要',
    subtitle: '从沟通要点形成 结构化客户服务记录',
    prompt:
      '根据预置沟通记录，生成 客户跟进纪要，提取客户态度、已确认事实、异议、后续动作、责任人与截止时间；未明确内容标记为“待确认”。',
  },
]

export const clientFacts = [
  { label: '管理资产', value: '¥1,286 万' },
  { label: '风险等级', value: 'C4 成长型' },
  { label: '服务等级', value: '重点客户 A' },
  { label: '最近联系', value: '2026-08-26' },
  { label: '短期资金需求', value: '¥150 万' },
  { label: '投资期限', value: '5 年以上' },
]
